typeset -U path PATH

path=(
  ~/.bin
  ~/.cargo/bin
  /usr/local/go/bin
  ~/go/bin
  ~/.local/bin
# ~/.sh
#  ~/.guard/bin
#  ~/.tfenv/bin
#   ${GOPATH}/bin
  $path
)

fpath=(
  ~/.zsh/functions
  $fpath
)

export EDITOR='nvim'

export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

export PIPENV_VENV_IN_PROJECT=1
